pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - or:
        - author=renovate[bot]
        - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
