name: Leptos CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Renovate Bot GitHub Action
      uses: renovatebot/github-action@v36.0.0
      env:
        RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features ssr --verbose

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features ssr --verbose
